name: medicare
description: A new Flutter project for AI-powered OPD prescription management.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0' # Updated to reflect latest stable Flutter/Dart SDK

dependencies:
  flutter:
    sdk: flutter
  
  # UI/UX and Core Flutter Utilities
  cupertino_icons: ^1.0.8 # Latest version
  provider: ^6.1.2 
  shared_preferences: ^2.2.3 

  # Audio Recording and File System Access
  record: ^6.0.0 
  path_provider: ^2.1.3 

  # HTTP Requests
  dio: ^5.4.3+1 

  # CSV File Parsing
  csv: ^5.1.1 

  # Firebase Dependencies for Backend Services (Authentication, Firestore)
  firebase_core: ^2.32.0 # Current latest for Firebase Core
  cloud_firestore: ^4.17.0 # Current latest for Cloud Firestore
  firebase_auth: ^4.19.0 # Current latest for Firebase Auth
  google_sign_in: ^6.2.1 

  # Utility for Generating Unique IDs
  uuid: ^4.5.0 
  
  # NEW: Audio Playback Library for TTS
  just_audio: ^0.9.36 

  intl: ^0.19.0 

  # PDF Generation and Printing
  pdf: ^3.10.8 # For PDF document creation
  printing: ^5.12.0 # For PDF preview and printing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/medicines.csv
    - assets/symptoms.csv
  
  # Fonts (Uncomment and configure if you have custom fonts, e.g., 'Inter')
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
