name: medicare
description: A new Flutter project for AI-powered OPD prescription management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/UX and Core Flutter Utilities
  cupertino_icons: ^1.0.8
  provider: ^6.1.2 
  shared_preferences: ^2.2.3 

  # Audio Recording and File System Access
  record: ^6.0.0
  path_provider: ^2.1.3 

  # HTTP Requests
  dio: ^5.4.3+1 

  # CSV File Parsing
  csv: ^5.1.1 

  # Firebase Dependencies
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1 

  # Utility for Generating Unique IDs
  uuid: ^4.5.0 
  url_launcher: ^6.3.0
  # Audio Playback
  just_audio: ^0.9.36 

  # Date Formatting
  intl: ^0.19.0 

  # PDF Generation and Printing
  pdf: ^3.10.8
  printing: ^5.12.0
  string_similarity: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/medicines_combined.json
    - assets/medicines.csv
    - assets/symptoms.csv


