// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9LuYTtGmscEzL2-Ixo8eS-7SFL-iCZ0',
    appId: '1:71218712902:web:61551c911990a650659547',
    messagingSenderId: '71218712902',
    projectId: 'medicare-fdaf4',
    authDomain: 'medicare-fdaf4.firebaseapp.com',
    storageBucket: 'medicare-fdaf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuzkYFOIgRWLyiyyWwWyessbqjTWW0lwI',
    appId: '1:71218712902:android:49763452307dad0d659547',
    messagingSenderId: '71218712902',
    projectId: 'medicare-fdaf4',
    storageBucket: 'medicare-fdaf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxhDaO4MEfpraumVJmnddIbK73sRchKgw',
    appId: '1:71218712902:ios:4fc4f94a454f9a81659547',
    messagingSenderId: '71218712902',
    projectId: 'medicare-fdaf4',
    storageBucket: 'medicare-fdaf4.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxhDaO4MEfpraumVJmnddIbK73sRchKgw',
    appId: '1:71218712902:ios:4fc4f94a454f9a81659547',
    messagingSenderId: '71218712902',
    projectId: 'medicare-fdaf4',
    storageBucket: 'medicare-fdaf4.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo9LuYTtGmscEzL2-Ixo8eS-7SFL-iCZ0',
    appId: '1:71218712902:web:b9b6dbc8dac13873659547',
    messagingSenderId: '71218712902',
    projectId: 'medicare-fdaf4',
    authDomain: 'medicare-fdaf4.firebaseapp.com',
    storageBucket: 'medicare-fdaf4.firebasestorage.app',
  );
}
